controller_manager:
  ros__parameters:
    update_rate: 100 # Hz
    use_sim_time: true

    robot_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster 
    robot_effort_controller:
      type: effort_controllers/JointGroupEffortController

robot_effort_controller:
  ros__parameters:
    joints:
      - left_wheel_joint
      - right_wheel_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort